# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 13f9c80798716d095be95cf1bcf94f1f956ef0f9f9972555ef3d95a4655878c9d4cca179f121817b0194e94e6b6572817eba5329c353f0feb613f8e734bc76d7

test:
  secret_key_base: ce9c742f6506cf373bd92da2918bfc425a7309d3b16a5079bd7e46289b70538268e88de8e9b176d06e82dd3220fc6fe92f1155f38b57052d43496df0599a807d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
